-- MySQL Script generated by MySQL Workbench
-- Sat Nov 17 11:10:23 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BDconsult` DEFAULT CHARACTER SET utf8 ;
USE `BDconsult` ;

-- -----------------------------------------------------
-- Table `mydb`.`pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDconsult`.`pais` (
  `idpais` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idpais`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDconsult`.`ciudad` (
  `idciudad` INT NOT NULL AUTO_INCREMENT,
  `pais_idpais` INT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idciudad`),
  INDEX `fk_ciudad_pais1_idx` (`pais_idpais` ASC),
  CONSTRAINT `fk_ciudad_pais1`
    FOREIGN KEY (`pais_idpais`)
    REFERENCES `BDconsult`.`pais` (`idpais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`concesionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDconsult`.`concesionario` (
  `idconcesionario` INT NOT NULL AUTO_INCREMENT,
  `razon_social` VARCHAR(45) NOT NULL,
  `rif` VARCHAR(45) NOT NULL,
  `telefono` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `pais_idpais` INT NOT NULL,
  `ciudad_idciudad` INT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idconcesionario`),
  INDEX `fk_concesionario_pais_idx` (`pais_idpais` ASC),
  INDEX `fk_concesionario_ciudad1_idx` (`ciudad_idciudad` ASC),
  CONSTRAINT `fk_concesionario_pais`
    FOREIGN KEY (`pais_idpais`)
    REFERENCES `BDconsult`.`pais` (`idpais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_concesionario_ciudad1`
    FOREIGN KEY (`ciudad_idciudad`)
    REFERENCES `BDconsult`.`ciudad` (`idciudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDconsult`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `nombrecol` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `cedula` INT(10) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `concesionario_idconcesionario` INT NOT NULL,
  PRIMARY KEY (`idcliente`),
  INDEX `fk_usuario_concesionario1_idx` (`concesionario_idconcesionario` ASC),
  CONSTRAINT `fk_usuario_concesionario1`
    FOREIGN KEY (`concesionario_idconcesionario`)
    REFERENCES `BDconsult`.`concesionario` (`idconcesionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
